defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  database: <%= ENV['DB_DATABASE'] %>
  template: template0
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *defaults
  database: <%= ENV['DB_DATABASE'] %>_development
test:
  <<: *defaults
  database: <%= ENV['DB_DATABASE'] %>_test
production:
  <<: *defaults
  database: <%= ENV['DB_DATABASE'] %>_production
